### ISSUE TITLE
No indication of service being started

### ISSUE THREAD

**Issue by fertkir** [hardpixel/systemd-manager#11]
When a systemd service has a long-running `ExecStartPre` script, its toggle isn't being switched on, so it looks like the service failed to start.
Would be good to add some indication that a service is being started.

**Comment by jonian** [comment]
Hi @fertkir, is there any `systemctl` command that can check if a process is being started?

**Comment by jonian** [comment]
The extension uses the `is-active` command to check if a service is enabled as you can see [here](https://github.com/hardpixel/systemd-manager/blob/38fa5702c5bb248f663416ee28e8bba8d7632c63/systemd-manager%40hardpixel.eu/utils.js#L46).

**Comment by fertkir** [comment]
You can use `status` and parse Active line:
```
systemctl status my.service 
● my.service - My service
     Loaded: loaded (/usr/local/lib/systemd/system/my.service; disa>
     Active: activating (start-pre)
```

**Comment by jonian** [comment]
Since the `isServiceActive` method will have to be replaced by `getServiceStatus`, what are the possible Active line values?

- inactive
- active
- activating

**Comment by jonian** [comment]
There is a better way to get the state, using show, because status is for user-readable output.

```sh
$ systemctl show docker --property=ActiveState
# ActiveState=active
```

**Comment by jonian** [comment]
Using `systemctl --state=help` I get the following output:

```
Available unit active states:

active
reloading
inactive
failed
activating
deactivating
maintenance
```
So for the extension we have to map them in 4 states:

- active (active)
- inactive (inactive)
- busy (reloading, activating, deactivating, maintenance)
- error (failed)

Not sure about maintenance. Any ideas on what it means?

**Comment by fertkir** [comment]
thank you!
