### ISSUE TITLE
[Feature] Please add support for masking services

### ISSUE THREAD

**Issue by benintech** [hardpixel/systemd-manager#12]
Is it possible to add support to mask and stop a service, instead of just stopping it ?

I sometimes mask the avahi-daemon service on some Wi-Fi networks, because I don't want any Wi-Fi printers popping up. Just stopping avahi-daemon is of no use, because it is automatically restarded. You need also to mask it.

It would be great if your extension would allow to mask and stop a service instead of just stopping it. Ideally this should be done on a per-service basis, allowing for each service to choose if toggling the switch just stops the service or also masks it.

**Comment by lazarosgogos** [comment]
Hello, is this project still alive? If so, I would like to contribute! :) @jonian

**Comment by jonian** [comment]
Fixed in PR #14 by @lazarosgogos.
