### ISSUE TITLE
Cannot use parameterized services

### ISSUE THREAD

**Issue by Haringat** [hardpixel/systemd-manager#2]
When I try to use this with parameterized services like `openvpn-client@.service` and pass a parameter (e.g. `openvpn-client@my.cloud.service`), it says that it could not find the service.

edit: fix the service names being recognized as e-mail addresses.

**Comment by jonian** [comment]
Hi @Haringat, thanks for the report. There is no support for parameterized services. I will try to add support in the next version. If you are willing to work on it, I will happily accept a PR.
